### ISSUE TITLE
Use receiver functions instead of passing nodes as function parameters

### ISSUE THREAD

**Issue by hieunguyenm** [CSIGildea/CS3012_Software_Engineering-LCA#2]
Instead of:
`func insert(tree *Tree, value int) *Tree {`

You can do:
`func (t *Tree) insert(value int) *Tree {`

**Comment by CSIGildea** [comment]
That function has been based on the insert function from golang.org/x/tour/tree as listed in the code.

I do see the point in making it tree,insert(...) over insert() but since I am not following any specific coding standard for this purpose, I am happy with it. I don't see a true functional benefit to doing so.

This really is a stylistic choice and if it is good enough for the official golang tour repo, it is good enough for me.

https://github.com/golang/tour/blob/master/tree/tree.go#L28
